---
kind: pipeline
name: default

clone:
  image: plugins/git
  depth: 1

steps:
- name: setup
  image: docker:git
  commands:
    - git clone --branch 4.2-dev https://github.com/joomla/joomla-cms.git

- name: phpcs
  image: joomlaprojects/docker-phpcs
  commands:
    - echo $(date)
    - /root/.composer/vendor/bin/phpcs --report=full --encoding=utf-8 --extensions=php -p --standard=joomla-cms/build/phpcs/Joomla src
    - echo $(date)
---
kind: signature
hmac: 82c4a2d9d6201cfc064d2b3253c2a48c6c7688f7f0595d72b392910c0fe2d72d

...
